/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ITreasuryOracle__factory } from './ITreasuryOracle__factory.js';
export { PDukaTreasury__factory } from './PDukaTreasury__factory.js';