/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ITreasuryOracle, ITreasuryOracleInterface } from "../../PDukaTreasury.sol/ITreasuryOracle.js";

  const _abi = [
  {
    "inputs": [],
    "name": "pdukaUsd",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class ITreasuryOracle__factory {
    static readonly abi = _abi;
    static createInterface(): ITreasuryOracleInterface {
      return new Interface(_abi) as ITreasuryOracleInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ITreasuryOracle {
      return new Contract(address, _abi, runner) as unknown as ITreasuryOracle;
    }
  }
  