/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface PDukaOracleInterface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_ADMIN_ROLE" | "ORACLE_ROLE" | "getRoleAdmin" | "grantRole" | "hasRole" | "isStale" | "lastUpdated" | "pdukaAmountToZar" | "pdukaToZar" | "pdukaUsd" | "renounceRole" | "revokeRole" | "setPdukaUsd" | "setStalenessThreshold" | "setUsdZar" | "stalenessThreshold" | "supportsInterface" | "updateRates" | "usdZar" | "useChainlinkForFx" | "zarToPduka"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "PdukaUsdUpdated" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "StalenessThresholdUpdated" | "UsdZarUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'ORACLE_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'isStale', values?: undefined): string;
encodeFunctionData(functionFragment: 'lastUpdated', values?: undefined): string;
encodeFunctionData(functionFragment: 'pdukaAmountToZar', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'pdukaToZar', values?: undefined): string;
encodeFunctionData(functionFragment: 'pdukaUsd', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setPdukaUsd', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setStalenessThreshold', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setUsdZar', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'stalenessThreshold', values?: undefined): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'updateRates', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'usdZar', values?: undefined): string;
encodeFunctionData(functionFragment: 'useChainlinkForFx', values?: undefined): string;
encodeFunctionData(functionFragment: 'zarToPduka', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ORACLE_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isStale', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastUpdated', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pdukaAmountToZar', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pdukaToZar', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pdukaUsd', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPdukaUsd', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setStalenessThreshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setUsdZar', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stalenessThreshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateRates', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdZar', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'useChainlinkForFx', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'zarToPduka', data: BytesLike): Result;
  }

  
    export namespace PdukaUsdUpdatedEvent {
      export type InputTuple = [oldRate: BigNumberish, newRate: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [oldRate: bigint, newRate: bigint, timestamp: bigint];
      export interface OutputObject {oldRate: bigint, newRate: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StalenessThresholdUpdatedEvent {
      export type InputTuple = [oldThreshold: BigNumberish, newThreshold: BigNumberish];
      export type OutputTuple = [oldThreshold: bigint, newThreshold: bigint];
      export interface OutputObject {oldThreshold: bigint, newThreshold: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UsdZarUpdatedEvent {
      export type InputTuple = [oldRate: BigNumberish, newRate: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [oldRate: bigint, newRate: bigint, timestamp: bigint];
      export interface OutputObject {oldRate: bigint, newRate: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PDukaOracle extends BaseContract {
    
    connect(runner?: ContractRunner | null): PDukaOracle;
    waitForDeployment(): Promise<this>;

    interface: PDukaOracleInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    ORACLE_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isStale: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    lastUpdated: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    pdukaAmountToZar: TypedContractMethod<
      [pdukaAmount: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    pdukaToZar: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    pdukaUsd: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setPdukaUsd: TypedContractMethod<
      [rate: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setStalenessThreshold: TypedContractMethod<
      [t: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setUsdZar: TypedContractMethod<
      [rate: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    stalenessThreshold: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    updateRates: TypedContractMethod<
      [_pdukaUsd: BigNumberish, _usdZar: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    usdZar: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    useChainlinkForFx: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    zarToPduka: TypedContractMethod<
      [zarAmount: BigNumberish, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'ORACLE_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isStale'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'lastUpdated'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'pdukaAmountToZar'): TypedContractMethod<
      [pdukaAmount: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'pdukaToZar'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'pdukaUsd'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPdukaUsd'): TypedContractMethod<
      [rate: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setStalenessThreshold'): TypedContractMethod<
      [t: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setUsdZar'): TypedContractMethod<
      [rate: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'stalenessThreshold'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'updateRates'): TypedContractMethod<
      [_pdukaUsd: BigNumberish, _usdZar: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usdZar'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'useChainlinkForFx'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'zarToPduka'): TypedContractMethod<
      [zarAmount: BigNumberish, ],
      [bigint],
      'view'
    >;

    getEvent(key: 'PdukaUsdUpdated'): TypedContractEvent<PdukaUsdUpdatedEvent.InputTuple, PdukaUsdUpdatedEvent.OutputTuple, PdukaUsdUpdatedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'StalenessThresholdUpdated'): TypedContractEvent<StalenessThresholdUpdatedEvent.InputTuple, StalenessThresholdUpdatedEvent.OutputTuple, StalenessThresholdUpdatedEvent.OutputObject>;
getEvent(key: 'UsdZarUpdated'): TypedContractEvent<UsdZarUpdatedEvent.InputTuple, UsdZarUpdatedEvent.OutputTuple, UsdZarUpdatedEvent.OutputObject>;

    filters: {
      
      'PdukaUsdUpdated(uint256,uint256,uint256)': TypedContractEvent<PdukaUsdUpdatedEvent.InputTuple, PdukaUsdUpdatedEvent.OutputTuple, PdukaUsdUpdatedEvent.OutputObject>;
      PdukaUsdUpdated: TypedContractEvent<PdukaUsdUpdatedEvent.InputTuple, PdukaUsdUpdatedEvent.OutputTuple, PdukaUsdUpdatedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'StalenessThresholdUpdated(uint256,uint256)': TypedContractEvent<StalenessThresholdUpdatedEvent.InputTuple, StalenessThresholdUpdatedEvent.OutputTuple, StalenessThresholdUpdatedEvent.OutputObject>;
      StalenessThresholdUpdated: TypedContractEvent<StalenessThresholdUpdatedEvent.InputTuple, StalenessThresholdUpdatedEvent.OutputTuple, StalenessThresholdUpdatedEvent.OutputObject>;
    

      'UsdZarUpdated(uint256,uint256,uint256)': TypedContractEvent<UsdZarUpdatedEvent.InputTuple, UsdZarUpdatedEvent.OutputTuple, UsdZarUpdatedEvent.OutputObject>;
      UsdZarUpdated: TypedContractEvent<UsdZarUpdatedEvent.InputTuple, UsdZarUpdatedEvent.OutputTuple, UsdZarUpdatedEvent.OutputObject>;
    
    };
  }