export enum LedgerEntryType {
  AVAILABLE = 'AVAILABLE',
  RESERVED = 'RESERVED',
  FEE = 'FEE',
  ADVANCE = 'ADVANCE',
  REFILL = 'REFILL',
  STAKE_LOCK = 'STAKE_LOCK',
  STAKE_UNLOCK = 'STAKE_UNLOCK',
  STAKING_REWARD = 'STAKING_REWARD',
}
