export enum TransactionType {
  PAYMENT = "PAYMENT",
  CASH_IN = "CASH_IN",
  CASH_OUT = "CASH_OUT",
  REMITTANCE_SEND = "REMITTANCE_SEND",
  REMITTANCE_COLLECT = "REMITTANCE_COLLECT",
  ADVANCE = "ADVANCE",
  REFILL = "REFILL",
  STAKING_REWARD = "STAKING_REWARD",
  WITHDRAWAL = "WITHDRAWAL",
  FEE = "FEE",
}
