/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IPDukaOracle, IPDukaOracleInterface } from "../../PDukaPool.sol/IPDukaOracle.js";

  const _abi = [
  {
    "inputs": [],
    "name": "isStale",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "pdukaAmount",
        "type": "uint256"
      }
    ],
    "name": "pdukaToZar",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "pdukaZar",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "zarAmount",
        "type": "uint256"
      }
    ],
    "name": "zarToPduka",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IPDukaOracle__factory {
    static readonly abi = _abi;
    static createInterface(): IPDukaOracleInterface {
      return new Interface(_abi) as IPDukaOracleInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IPDukaOracle {
      return new Contract(address, _abi, runner) as unknown as IPDukaOracle;
    }
  }
  