/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IPDukaTreasury, IPDukaTreasuryInterface } from "../../PDukaPool.sol/IPDukaTreasury.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "receiveFunds",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IPDukaTreasury__factory {
    static readonly abi = _abi;
    static createInterface(): IPDukaTreasuryInterface {
      return new Interface(_abi) as IPDukaTreasuryInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IPDukaTreasury {
      return new Contract(address, _abi, runner) as unknown as IPDukaTreasury;
    }
  }
  