/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPDukaOracle } from './IPDukaOracle.js';
export type { IPDukaTreasury } from './IPDukaTreasury.js';
export type { PDukaPool } from './PDukaPool.js';