/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IPDukaOracleInterface extends Interface {
    getFunction(nameOrSignature: "isStale" | "pdukaToZar" | "pdukaZar" | "zarToPduka"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'isStale', values?: undefined): string;
encodeFunctionData(functionFragment: 'pdukaToZar', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'pdukaZar', values?: undefined): string;
encodeFunctionData(functionFragment: 'zarToPduka', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'isStale', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pdukaToZar', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pdukaZar', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'zarToPduka', data: BytesLike): Result;
  }

  

  export interface IPDukaOracle extends BaseContract {
    
    connect(runner?: ContractRunner | null): IPDukaOracle;
    waitForDeployment(): Promise<this>;

    interface: IPDukaOracleInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    isStale: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    pdukaToZar: TypedContractMethod<
      [pdukaAmount: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    pdukaZar: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    zarToPduka: TypedContractMethod<
      [zarAmount: BigNumberish, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'isStale'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'pdukaToZar'): TypedContractMethod<
      [pdukaAmount: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'pdukaZar'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'zarToPduka'): TypedContractMethod<
      [zarAmount: BigNumberish, ],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }