/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ITreasuryOracle } from './ITreasuryOracle.js';
export type { PDukaTreasury } from './PDukaTreasury.js';