/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface PDukaTreasuryInterface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_ADMIN_ROLE" | "OPERATOR_ROLE" | "ORACLE_ROLE" | "addVault" | "disburse" | "getRoleAdmin" | "getVaultInfo" | "grantRole" | "hasRole" | "isVault" | "maxPerVaultUsd" | "maxTokensPerVault" | "oracle" | "pause" | "paused" | "pduka" | "rebalance" | "receiveFunds" | "removeVault" | "renounceRole" | "revokeRole" | "setMaxPerVaultUsd" | "supportsInterface" | "totalAssignedToVaults" | "totalDisbursed" | "totalReceived" | "totalTreasuryBalance" | "unassignedBalance" | "unpause" | "vaultBalance" | "vaultCount" | "vaults"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "FundsDisbursed" | "FundsReceived" | "MaxPerVaultUpdated" | "Paused" | "RateUpdated" | "Rebalanced" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "Unpaused" | "VaultAdded" | "VaultRemoved"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'OPERATOR_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'ORACLE_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'addVault', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'disburse', values: [AddressLike, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getVaultInfo', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'isVault', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'maxPerVaultUsd', values?: undefined): string;
encodeFunctionData(functionFragment: 'maxTokensPerVault', values?: undefined): string;
encodeFunctionData(functionFragment: 'oracle', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'pduka', values?: undefined): string;
encodeFunctionData(functionFragment: 'rebalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'receiveFunds', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'removeVault', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setMaxPerVaultUsd', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'totalAssignedToVaults', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalDisbursed', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalReceived', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalTreasuryBalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'unassignedBalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'vaultBalance', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'vaultCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'vaults', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'OPERATOR_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ORACLE_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addVault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'disburse', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getVaultInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isVault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maxPerVaultUsd', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maxTokensPerVault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'oracle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pduka', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rebalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'receiveFunds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeVault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMaxPerVaultUsd', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalAssignedToVaults', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalDisbursed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalReceived', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalTreasuryBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unassignedBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vaultBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vaultCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vaults', data: BytesLike): Result;
  }

  
    export namespace FundsDisbursedEvent {
      export type InputTuple = [vault: AddressLike, to: AddressLike, amount: BigNumberish, reason: BytesLike];
      export type OutputTuple = [vault: string, to: string, amount: bigint, reason: string];
      export interface OutputObject {vault: string, to: string, amount: bigint, reason: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FundsReceivedEvent {
      export type InputTuple = [amount: BigNumberish, routed_to: AddressLike, vaultNewBalance: BigNumberish];
      export type OutputTuple = [amount: bigint, routed_to: string, vaultNewBalance: bigint];
      export interface OutputObject {amount: bigint, routed_to: string, vaultNewBalance: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MaxPerVaultUpdatedEvent {
      export type InputTuple = [oldMax: BigNumberish, newMax: BigNumberish];
      export type OutputTuple = [oldMax: bigint, newMax: bigint];
      export interface OutputObject {oldMax: bigint, newMax: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RateUpdatedEvent {
      export type InputTuple = [oldRate: BigNumberish, newRate: BigNumberish];
      export type OutputTuple = [oldRate: bigint, newRate: bigint];
      export interface OutputObject {oldRate: bigint, newRate: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RebalancedEvent {
      export type InputTuple = [vaultsAffected: BigNumberish];
      export type OutputTuple = [vaultsAffected: bigint];
      export interface OutputObject {vaultsAffected: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VaultAddedEvent {
      export type InputTuple = [vault: AddressLike, index: BigNumberish];
      export type OutputTuple = [vault: string, index: bigint];
      export interface OutputObject {vault: string, index: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VaultRemovedEvent {
      export type InputTuple = [vault: AddressLike];
      export type OutputTuple = [vault: string];
      export interface OutputObject {vault: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PDukaTreasury extends BaseContract {
    
    connect(runner?: ContractRunner | null): PDukaTreasury;
    waitForDeployment(): Promise<this>;

    interface: PDukaTreasuryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    OPERATOR_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    ORACLE_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    addVault: TypedContractMethod<
      [vault: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    disburse: TypedContractMethod<
      [vault: AddressLike, to: AddressLike, amount: BigNumberish, reason: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    getVaultInfo: TypedContractMethod<
      [index: BigNumberish, ],
      [[string, bigint, bigint] & {vault: string, balance: bigint, capacityRemaining: bigint }],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isVault: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    maxPerVaultUsd: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    maxTokensPerVault: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    oracle: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    pduka: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    rebalance: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    receiveFunds: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    removeVault: TypedContractMethod<
      [vault: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setMaxPerVaultUsd: TypedContractMethod<
      [newMax: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    totalAssignedToVaults: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalDisbursed: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalReceived: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalTreasuryBalance: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    unassignedBalance: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    vaultBalance: TypedContractMethod<
      [index: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    vaultCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    vaults: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'OPERATOR_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'ORACLE_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'addVault'): TypedContractMethod<
      [vault: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'disburse'): TypedContractMethod<
      [vault: AddressLike, to: AddressLike, amount: BigNumberish, reason: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getVaultInfo'): TypedContractMethod<
      [index: BigNumberish, ],
      [[string, bigint, bigint] & {vault: string, balance: bigint, capacityRemaining: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isVault'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'maxPerVaultUsd'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'maxTokensPerVault'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'oracle'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'pduka'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'rebalance'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'receiveFunds'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeVault'): TypedContractMethod<
      [vault: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMaxPerVaultUsd'): TypedContractMethod<
      [newMax: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'totalAssignedToVaults'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalDisbursed'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalReceived'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalTreasuryBalance'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'unassignedBalance'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'vaultBalance'): TypedContractMethod<
      [index: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'vaultCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'vaults'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;

    getEvent(key: 'FundsDisbursed'): TypedContractEvent<FundsDisbursedEvent.InputTuple, FundsDisbursedEvent.OutputTuple, FundsDisbursedEvent.OutputObject>;
getEvent(key: 'FundsReceived'): TypedContractEvent<FundsReceivedEvent.InputTuple, FundsReceivedEvent.OutputTuple, FundsReceivedEvent.OutputObject>;
getEvent(key: 'MaxPerVaultUpdated'): TypedContractEvent<MaxPerVaultUpdatedEvent.InputTuple, MaxPerVaultUpdatedEvent.OutputTuple, MaxPerVaultUpdatedEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'RateUpdated'): TypedContractEvent<RateUpdatedEvent.InputTuple, RateUpdatedEvent.OutputTuple, RateUpdatedEvent.OutputObject>;
getEvent(key: 'Rebalanced'): TypedContractEvent<RebalancedEvent.InputTuple, RebalancedEvent.OutputTuple, RebalancedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
getEvent(key: 'VaultAdded'): TypedContractEvent<VaultAddedEvent.InputTuple, VaultAddedEvent.OutputTuple, VaultAddedEvent.OutputObject>;
getEvent(key: 'VaultRemoved'): TypedContractEvent<VaultRemovedEvent.InputTuple, VaultRemovedEvent.OutputTuple, VaultRemovedEvent.OutputObject>;

    filters: {
      
      'FundsDisbursed(address,address,uint256,bytes32)': TypedContractEvent<FundsDisbursedEvent.InputTuple, FundsDisbursedEvent.OutputTuple, FundsDisbursedEvent.OutputObject>;
      FundsDisbursed: TypedContractEvent<FundsDisbursedEvent.InputTuple, FundsDisbursedEvent.OutputTuple, FundsDisbursedEvent.OutputObject>;
    

      'FundsReceived(uint256,address,uint256)': TypedContractEvent<FundsReceivedEvent.InputTuple, FundsReceivedEvent.OutputTuple, FundsReceivedEvent.OutputObject>;
      FundsReceived: TypedContractEvent<FundsReceivedEvent.InputTuple, FundsReceivedEvent.OutputTuple, FundsReceivedEvent.OutputObject>;
    

      'MaxPerVaultUpdated(uint256,uint256)': TypedContractEvent<MaxPerVaultUpdatedEvent.InputTuple, MaxPerVaultUpdatedEvent.OutputTuple, MaxPerVaultUpdatedEvent.OutputObject>;
      MaxPerVaultUpdated: TypedContractEvent<MaxPerVaultUpdatedEvent.InputTuple, MaxPerVaultUpdatedEvent.OutputTuple, MaxPerVaultUpdatedEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'RateUpdated(uint256,uint256)': TypedContractEvent<RateUpdatedEvent.InputTuple, RateUpdatedEvent.OutputTuple, RateUpdatedEvent.OutputObject>;
      RateUpdated: TypedContractEvent<RateUpdatedEvent.InputTuple, RateUpdatedEvent.OutputTuple, RateUpdatedEvent.OutputObject>;
    

      'Rebalanced(uint256)': TypedContractEvent<RebalancedEvent.InputTuple, RebalancedEvent.OutputTuple, RebalancedEvent.OutputObject>;
      Rebalanced: TypedContractEvent<RebalancedEvent.InputTuple, RebalancedEvent.OutputTuple, RebalancedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    

      'VaultAdded(address,uint256)': TypedContractEvent<VaultAddedEvent.InputTuple, VaultAddedEvent.OutputTuple, VaultAddedEvent.OutputObject>;
      VaultAdded: TypedContractEvent<VaultAddedEvent.InputTuple, VaultAddedEvent.OutputTuple, VaultAddedEvent.OutputObject>;
    

      'VaultRemoved(address)': TypedContractEvent<VaultRemovedEvent.InputTuple, VaultRemovedEvent.OutputTuple, VaultRemovedEvent.OutputObject>;
      VaultRemoved: TypedContractEvent<VaultRemovedEvent.InputTuple, VaultRemovedEvent.OutputTuple, VaultRemovedEvent.OutputObject>;
    
    };
  }