export enum LedgerEntryType {
  AVAILABLE = 'AVAILABLE',
  RESERVED = 'RESERVED',
  FEE = 'FEE',
  ADVANCE = 'ADVANCE',
  REFILL = 'REFILL',
  CASH_IN = 'CASH_IN',
  CASH_OUT = 'CASH_OUT',
  REMITTANCE_IN = 'REMITTANCE_IN',
  REMITTANCE_OUT = 'REMITTANCE_OUT',
  COMMISSION = 'COMMISSION',
}
