export enum RemittanceStatus {
  INITIATED = 'INITIATED',
  FUNDS_HELD = 'FUNDS_HELD',
  READY_FOR_COLLECTION = 'READY_FOR_COLLECTION',
  COLLECTED = 'COLLECTED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}
